const reviews = [
  {
    id: 1,
    name: "Mohit Prajapati",
    job: "Software Engineer",
    image: "https://media.licdn.com/dms/image/v2/D5603AQEM_AuXg9Eiyg/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1720978931375?e=1744848000&v=beta&t=OEGJxZL6iBVbpHHFPm7opVvYZXTt70R9WmIZcWYNdKI",
    text: "Working with this team was a pleasure. Their technical expertise and ability to deliver quality solutions on time and within budget were impressive. I highly recommend them as a true partner and asset to any project.",
  },
  {
    id: 2,
    name: "Pranay Gupta",
    job: "Software Engineer",
    image: "https://aeccc.targettechnology.in/static/media/PranayGupta.f3c530b7630ba8efb2ab.jpg",
    text: "I have had the pleasure of working with this team on several projects, and I am consistently impressed with their technical expertise and ability to deliver quality solutions on time and within budget. They are a true partner and an asset to any project.",
  },
  {
    id: 3,
    name: "Abir Pal",
    job: "Graphic Designer",
    image: "https://aeccc.targettechnology.in/static/media/AbirPal.574a09ad7cb325853b29.jpg",
    text: "I have been working with this company for several years now, and I have always been impressed with their creativity and attention to detail. They are true professionals who take pride in their work and always go above and beyond to deliver exceptional results.",
  },
  {
    id: 4,
    name: "Soumya Banerjee",
    job: "Marketing Manager",
    image: "https://aeccc.targettechnology.in/static/media/SoumyaBanerjee.2e2521d6029842435080.jpg",
    text: "I am thrilled with the results of our recent marketing campaign, and it wouldn't have been possible without the hard work and dedication of the entire team. Thank you for your exceptional work!",
  },
  {
    id: 5,
    name: "Saikat Mukherjee",
    job: "Content Strategist",
    image: "https://aeccc.targettechnology.in/static/media/SaikatMukherjee.033310703edff52d0532.jpg",
    text: "I have worked with many content creators over the years, but none have impressed me as much as this team. They have a knack for crafting compelling and engaging content that resonates with our audience and drives real results. I highly recommend them!",
  },
  {
    id: 6,
    name: "Aritra Biswas",
    job: "Data Analyst",
    image: "https://avatars.githubusercontent.com/u/93366359?v=4",
    text: "I had the opportunity to work with this team on a data analysis project, and I was impressed with their attention to detail and their ability to work with complex datasets. They provided valuable insights that helped us make informed business decisions. It was a pleasure working with them.",
  },
  
    {
      id: 7,
      name: "Shreya Kapoor",
      job: "AI Researcher",
      image: "https://randomuser.me/api/portraits/women/44.jpg",
      text: "Collaborating with this team on an AI project was a fantastic experience. Their ability to solve complex problems and innovate was truly inspiring. I highly recommend their services for any AI-related initiatives.",
    },
    {
      id: 8,
      name: "Rahul Verma",
      job: "Data Scientist",
      image: "https://randomuser.me/api/portraits/men/45.jpg",
      text: "Working on a predictive modeling project with this team was a great experience. They delivered actionable insights through their expertise in data preprocessing and advanced analytics.",
    },
    {
      id: 9,
      name: "Priya Singh",
      job: "Machine Learning Engineer",
      image: "https://randomuser.me/api/portraits/women/46.jpg",
      text: "Their knowledge of machine learning algorithms and frameworks is unparalleled. They were instrumental in building robust and scalable ML solutions for our organization.",
    },
    {
      id: 10,
      name: "Aditya Roy",
      job: "DevOps Engineer",
      image: "https://randomuser.me/api/portraits/men/47.jpg",
      text: "The team's DevOps skills and automation expertise transformed our development pipeline, improving efficiency and reducing deployment times. They truly understand modern DevOps practices.",
    },
    {
      id: 11,
      name: "Kavya Mehta",
      job: "Cloud Engineer",
      image: "https://randomuser.me/api/portraits/women/48.jpg",
      text: "I had the privilege of working with them on a cloud migration project. Their deep understanding of AWS and Azure services ensured a smooth and cost-effective transition.",
    },
    {
      id: 12,
      name: "Vikram Sharma",
      job: "Frontend Developer",
      image: "https://randomuser.me/api/portraits/men/49.jpg",
      text: "Their expertise in React.js and attention to detail resulted in an intuitive and visually stunning user interface for our web application.",
    },
    {
      id: 13,
      name: "Ananya Gupta",
      job: "Backend Developer",
      image: "https://randomuser.me/api/portraits/women/50.jpg",
      text: "Their ability to design and implement scalable backend systems using Node.js and Express.js was pivotal in the success of our project.",
    },
    {
      id: 14,
      name: "Rohit Das",
      job: "Full-Stack Developer",
      image: "https://randomuser.me/api/portraits/men/51.jpg",
      text: "The team's proficiency in full-stack development and seamless integration of frontend and backend technologies was remarkable. Highly recommended for any development project.",
    },
    {
      id: 15,
      name: "Nisha Agarwal",
      job: "UI/UX Designer",
      image: "https://randomuser.me/api/portraits/women/52.jpg",
      text: "Their creativity and ability to design user-friendly interfaces exceeded all expectations. The final product was visually appealing and highly functional.",
    },
    {
      id: 16,
      name: "Manoj Tiwari",
      job: "Cybersecurity Analyst",
      image: "https://randomuser.me/api/portraits/men/53.jpg",
      text: "They implemented robust security measures that safeguarded our data and infrastructure. Their expertise in cybersecurity is unparalleled.",
    },
    {
      id: 17,
      name: "Neha Rathi",
      job: "Big Data Engineer",
      image: "https://randomuser.me/api/portraits/women/54.jpg",
      text: "The team’s ability to process and analyze massive datasets using Hadoop and Spark was crucial for our data-driven strategies.",
    },
    {
      id: 18,
      name: "Sandeep Kulkarni",
      job: "QA Engineer",
      image: "https://randomuser.me/api/portraits/men/55.jpg",
      text: "Their attention to detail and rigorous testing methodologies ensured the quality and reliability of our software products.",
    },
    {
      id: 19,
      name: "Isha Malhotra",
      job: "Mobile App Developer",
      image: "https://randomuser.me/api/portraits/women/56.jpg",
      text: "They developed a high-performance and feature-rich mobile application that has received excellent user feedback.",
    },
    {
      id: 20,
      name: "Arjun Bhardwaj",
      job: "Blockchain Developer",
      image: "https://randomuser.me/api/portraits/men/57.jpg",
      text: "Their expertise in blockchain technologies and smart contracts helped us launch a secure and decentralized application with ease.",
    },
    {
      id: 21,
      name: "Sneha Joshi",
      job: "NLP Engineer",
      image: "https://randomuser.me/api/portraits/women/58.jpg",
      text: "Their work on natural language processing projects, including sentiment analysis and chatbot development, was exceptional.",
    }
  

];

export default reviews;
